
spring:
  servlet:
    multipart:
      file-size-threshold: 1MB
      location: C:/Users/jemin/IdeaProjects/finaltoyproject/src/main/java/finaltoyproject/public/upload/
      max-file-size: 100MB
      max-request-size: 100MB
  #   redis:
#    host: localhost
#    port: 6379
#  session:
#    redis:
#      flush-mode: on_save
#      namespace: spring:session
#    store-type: redis
  #  cache:
  #    type: redis
  #    redis:
  #      cache-null-values: true
  #      time-to-live: 10000
  datasource:

    url: jdbc:mysql://localhost:3306/toyproject_schema?serverTimezone=UTC&characterEncoding=UTF-8

    username: root
    password: 4321
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true
        use_sql_comments: true
jwt:
  header: Authorization
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  token-validity-in-seconds: 86400

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace
server:
  port: 8083
