spring:
  redis:
    host: localhost
    port: 6379
    session:
      redis:
        flush-mode: on_save # 호출될때만 redis에 기록, immediate는 즉시 기록
        namespace: spring:session # timeout springbootapplication에 붙임
      store-type: redis
  datasource:
    url: jdbc:mysql://rdstest.coszpbcqim9m.ap-northeast-2.rds.amazonaws.com:3306/finalproject?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: sjmin
    password: 71312m**0312
    driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          default_batch_fetch_size: 100
          # show_sql: true
          format_sql: true
          use_sql_comments: true

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace
server:
  port: 8081