spring:
  datasource:
    url: jdbc:mysql://localhost:3306/toyproject_schema?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 4321
    driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          default_batch_fetch_size: 100
          # show_sql: true
          format_sql: true
          use_sql_comments: true