# This is a basic workflow to help you get started with Actions

name: finalproject


on:
  workflow_dispatch:

# env: 
#  S3_BUCKET_NAME: logging-system-deploy-jm
#  PROJECT_NAME: actionsdeploy

jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        shell: bash
        
      - name: Setup MySQL
        uses: mirromutth/mysql-action@v1.1
        with:
          host port: 8080
          container port: 3306
          mysql version: '5.7'
          mysql database: toy_schema
          mysql user: 'root'
          mysql password: '4321'


      - name: Build with Gradle
        run: ./gradlew build
        shell: bash
